version: '3.3'

networks:
  static:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16


services:
  db:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=sod8fuskfjsnfkbs__at4etragfs
      - MYSQL_PASSWORD=sod8fuskfjsnfkbs__at4etragfs
    volumes:
      - ./initDB:/docker-entrypoint-initdb.d # creating databases
    ports:
      - "3306:3306"
    networks:
      static:
        ipv4_address: 10.5.0.5


  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: sod8fuskfjsnfkbs__at4etragfs


  dj_fam:
    depends_on:
      - db
    image: my_first_docker
    restart: always
    ports:
      - '8000:8000'
    environment:
      DB: db
      MYSQL_PASSWORD: sod8fuskfjsnfkbs__at4etragfs

    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"