# Generated by Django 3.2.3 on 2021-05-13 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='human',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=50)),
            ],
        ),
    ]
