# Generated by Django 3.2.3 on 2021-05-13 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
