# Generated by Django 3.2.3 on 2021-05-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fam', '0002_alter_human_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='human',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
