# Generated by Django 3.2.3 on 2021-05-18 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fam', '0003_auto_20210518_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='human',
            name='height',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='human',
            name='weight',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
