# Generated by Django 3.2.3 on 2021-05-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fam', '0004_auto_20210518_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
